apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: creatio-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SirSabek/Creatio-GitOps
    targetRevision: main
    path: App/Creatio/base
  destination:
    server: https://kubernetes.default.svc
    namespace: creatio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
